# 캐니 에지 검출기

In [9]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

* 허프 변환 원 검출

In [2]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

In [14]:
edges1 = cv2.Canny(src, 50, 100) # 1 : 2 or 1 : 3의 비율을 권장.
edges2 = cv2.Canny(src, 50, 150)
edges3 = cv2.Canny(src, 50, 200)

cv2.imshow('edges1', edges1)
cv2.imshow('edges2', edges2)
cv2.imshow('edges3', edges3)
cv2.waitKey()
cv2.destroyAllWindows()

In [24]:
src = cv2.imread('./data/rect.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray, 50, 100)
lines = cv2.HoughLines(edges, rho=1, theta=np.pi/180.0, threshold=100)

for line in lines:
    rho, theta   = line[0]
    c = np.cos(theta)
    s = np.sin(theta)
    x0 = c*rho
    y0  = s*rho
    print("x0, y0", x0, y0)
    x1 = int(x0 + 1000*(-s))
    y1 = int(y0 + 1000*(c))
    print("x1, y1", x1, y1)
    x2 = int(x0 - 1000*(-s))
    y2 = int(y0 - 1000*(c))
    print("x2, y2", x2, y2)
    cv2.line(src, (x1,y1), (x2,y2), (0,0,255), 2)
    
cv2.imshow('src', src)
cv2.imshow('edges', edges)
cv2.waitKey()
cv2.destroyAllWindows()

x0, y0 -1.4337335e-05 328.0
x1, y1 -1000 327
x2, y2 999 328
x0, y0 356.0 0.0
x1, y1 356 1000
x2, y2 356 -1000
x0, y0 -5.0268095e-06 115.0
x1, y1 -1000 114
x2, y2 999 115
x0, y0 137.0 0.0
x1, y1 137 1000
x2, y2 137 -1000


In [40]:
src = cv2.imread('./data/building.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray, 50, 100)
lines = cv2.HoughLines(edges, rho=1, theta=np.pi/180.0, threshold=160)

In [41]:
lines.shape

(11368, 1, 2)

In [42]:
edges.shape

(600, 868)

In [114]:
src = cv2.imread('./data/building.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray, 50, 100)
edge = cv2.merge([edges, edges, edges])
lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180.0, threshold=160, minLineLength=150, maxLineGap = 10)

for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(edge, (x1, y1), (x2, y2), (0, 0, 255), 2)
    
cv2.imshow('src', src)
cv2.imshow('edges', edge)
cv2.waitKey()
cv2.destroyAllWindows()    

In [45]:
src.shape

(600, 868, 3)

* 허프 변환 원 검출

In [ ]:
circles.shape

circles[0]  #3차원 배열이라 2차원으로 축소

In [155]:
src = cv2.imread('./data/circles.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

circles = cv2.HoughCircles(gray, method=cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=15)

for circle in circles[0]:
    print(circle)
    cx, cy, r = circle
    cv2.circle(src, (np.uint32(cx), np.uint32(cy)), np.uint32(r), (0, 0, 255), 2)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()    

[228.5 220.5  76.1]
[369.5 147.5  62.2]
[344.5 391.5  53.2]


In [173]:
src = cv2.imread('./data/circles2.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

circles = cv2.HoughCircles(gray, method=cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=15, minRadius=30, maxRadius=100)

for circle in circles[0]:
    print(circle)
    cx, cy, r = circle
    cv2.circle(src, (np.uint32(cx), np.uint32(cy)), np.uint32(r), (0, 0, 255), 2)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()    

[370.5 147.5  62.2]
[345.5 391.5  53. ]
[229.5 219.5  75.2]
[242.5 385.5  47.2]
[429.5 233.5  54.4]
[119.5 219.5  49.2]


In [191]:
src = cv2.imread('./data/coins.png')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

circles = cv2.HoughCircles(gray, method=cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=15, minRadius=11, maxRadius=32)

for circle in circles[0]:
    print(circle)
    cx, cy, r = circle
    cv2.circle(src, (np.uint32(cx), np.uint32(cy)), np.uint32(r), (0, 0, 255), 2)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()    

[216.5  70.5  28.8]
[173.5 119.5  29. ]
[234.5 172.5  24.3]
[120.5 207.5  29.2]
[ 36.5 105.5  29.2]
[148.5  33.5  28.2]
[265.5 101.5  24. ]
[56.5 48.5 23.2]
[108.5  83.5  24.1]
[ 95.5 148.5  28. ]


In [176]:
circles

array([[[163.5, 125.5,  79.6],
        [108.5,  85.5,  74.1],
        [133.5,  37.5,  99.4],
        [204.5, 160.5,  99.4],
        [ 79.5, 148.5,  79.6],
        [170.5,  72.5,  48.7],
        [156.5, 185.5,  68.5],
        [ 53.5, 104.5,  46.3],
        [210.5, 107.5,  51.6],
        [ 62.5,  41.5,  83.9],
        [ 58.5, 197.5,  71.8],
        [251.5, 137.5,  53. ],
        [214.5,  46.5,  79.6],
        [  5.5, 140.5,  99.4],
        [279.5,  32.5,  81.7],
        [215.5, 211.5,  99.4],
        [ 12.5,  60.5,  40.2],
        [108.5, 199.5,  42.5],
        [258.5,  80.5,  35.1],
        [176.5,   8.5,  46.3],
        [ 79.5, 243.5,  61.2],
        [259.5, 187.5,  32.1]]], dtype=float32)