* 키보드 이벤트 처리

In [1]:
import cv2
import numpy as np

In [35]:
width, height = 512, 512
x, y = width//2, height//2
R = 50 #radius
derection = 0 # 0 : right,  1: down, 2:left, 3: up

In [32]:
x - R

412

In [33]:
x

462

In [36]:
while True:
    key = cv2.waitKeyEx(30)
    if key == 0x1B: # 24의 헥사값 esc인듯
        break
    # 방향키 처리
    elif key == 0x270000: # right 우측 방향키
        direction = 0
    elif key == 0x280000: # down 하단 방향
        direction = 1
    elif key == 0x250000: # left 좌측
        direction = 2
    elif key == 0x260000: # up 상단
        direction = 3
    #direction으로 x y좌표를 바꿔주면 된다.

    # 방향에 맞게 x, y 좌표 설정
    if direction == 0:
        x += 10
    elif direction == 1:
        y += 10
    elif direction == 2:
        x -= 10
    else:  #3인경우지만 평소에도 우측으로 가게끔 하려고
        y -= 10
    
    # 경계확인
    if x <= R:
        x = R
        direction = 0
    if x > width - R:
        x = width - R
        direction = 2
    if y < R:
        y = R
        direction = 1
    if y > height - R:
        y = height - R
        direction = 3
    
    # 지우기, 그리기
    img = np.zeros((width, height, 3), np.uint8) + 255
    cv2.circle(img, (x, y), R, (0, 0, 255), -1)
    cv2.imshow('img', img)

cv2.destroyAllWindows()

* 마우스 이벤트 처리

In [197]:
img = np.zeros((512, 512, 3), np.uint8) + 255

def onMouse(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        if flags & cv2.EVENT_FLAG_SHIFTKEY:
            cv2.rectangle(param[0], (x - 5, y - 5), (x + 5, y + 5), (255, 0, 0))
        else:
            cv2.circle(param[0], (x, y), 5, (255, 0, 0), 3) #param이 여러개를 받아와서 색인으로 해야함
    elif event == cv2.EVENT_RBUTTONDOWN:
        cv2.circle(param[0],(x, y), 5, (0, 0, 255), 3)
    elif event == cv2.EVENT_LBUTTONDBLCLK:
        param[0] = np.zeros((512, 512, 3), np.uint8) + 255
    cv2.imshow('img', param[0])
#######################################

cv2.imshow('img', img)


cv2.setMouseCallback('img', onMouse, [img]) #[img] 처럼 파라미터 지정 가능
cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import cv2
import numpy as np

* 트랙바 이벤트 처리

In [16]:
def onChange(pos):
    global img
    r = cv2.getTrackbarPos('R', 'img')
    g = cv2.getTrackbarPos('G', 'img')
    b = cv2.getTrackbarPos('B', 'img')
    
    img[:] = (b, g, r) #img에 그대로 받으면 이미지의 사이즈가 RGB만큼으로 변해버려서 전체를 바꾸려면 내부 value를 받아야한다.
    cv2.imshow('img', img)
    
img = np.zeros((512, 512, 3), np.uint8) + 255

cv2.imshow('img', img)

#cv2.createTrackbar('트랙바 이름', 넣을 프레임 이름, min, max, 처리 함수)
cv2.createTrackbar('R', 'img', 0, 255, onChange)
cv2.createTrackbar('G', 'img', 0, 255, onChange)
cv2.createTrackbar('B', 'img', 0, 255, onChange)

cv2.setTrackbarPos('B', 'img', 255)

cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
img[:,:, 2].shape

(512, 512)

In [11]:
img[:].shape

(512, 512, 3)

In [13]:
img.shape

(512, 512, 3)

In [17]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [18]:
a1[1:] # 2, 3 
a1[:2] # 1, 2

array([2, 3])

In [23]:
a2[0,1:] #행, 열이라고 생각하면 쉽다.
a2[1,1:]

array([5, 6])

## OpenCV 기본연산

* 형상(shape), 자료형(dtype) 확인

In [4]:
img = cv2.imread('./data/Lena.jpg') #cv2.IMREAD_COLOR

In [5]:
img.ndim #3차원

3

In [6]:
img.shape # (512, 512)가 세장 있다 b g r이렇게 세개

(512, 512, 3)

In [7]:
img.dtype #양수이고 255까지라서 uint의 8비트 인듯

dtype('uint8')

In [8]:
img = img.astype(np.int32)

In [9]:
img.dtype

dtype('int32')

In [10]:
img = np.uint8(img) #함수 통과도 가능 int()랑 동일.

In [11]:
img.dtype

dtype('uint8')

* 모양 변경하기

In [12]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

In [13]:
img.shape

(512, 512)

In [14]:
512 * 512 #flat은 일차원으로 만들어준다.

262144

In [15]:
img = img.flatten()

In [16]:
img.shape

(262144,)

In [17]:
img = img.reshape(512, 512)

In [18]:
img.shape

(512, 512)

In [19]:
img = img.flatten()

In [20]:
img = img.reshape(-1, 512, 512)

In [21]:
img.shape # 3차원 512 512 1하고 비슷한듯

(1, 512, 512)

In [26]:
cv2.imshow('img', img[0,:,:])
cv2.waitKey()
cv2.destroyAllWindows()

* 화소 접근 1 : 그레이 스케일 영상

In [37]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
img # 512, 512

img[100, 200] = 0
img[100: 400, 200:300] = 0 #이때는 np라서 200열의 100번째 행으로 간다.

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

array([[163, 162, 161, ..., 170, 154, 130],
       [162, 162, 162, ..., 173, 155, 126],
       [162, 162, 163, ..., 170, 155, 128],
       ...,
       [ 43,  42,  51, ..., 103, 101,  99],
       [ 41,  42,  55, ..., 103, 105, 106],
       [ 42,  44,  57, ..., 102, 106, 109]], dtype=uint8)

In [38]:
img[100: 400, 200:300] = 0 #이때는 np라서 200열의 100번째 행으로 간다.

In [39]:
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

* 화소 접근 2 : 컬러 영상

In [55]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
 
img[100, 200] = 0
img[100: 400, 200:300] = 0

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

* 화소 접근 3 : 채널 접근

In [54]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_COLOR)
 
img[100: 400, 200:300, 0] = 255 # BlueChanel
img[100: 400, 200:300, 1] = 0   # Green
img[100: 400, 200:300, 2] = 255 # Red

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

* 마우스로 ROI(관심영역) 영역 지정  : selectROI()

In [24]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src)
x = roi[:2]
y = roi[2:]
img = src[roi[1]:roi[1] + roi[3], roi[0]:roi[0]+roi[2]]

#cv2.rectangle(src, x, y, (255, 255, 255), 3)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
cv2.destroyAllWindows()

In [14]:
roi #x, y, x , y가 나온다. 좌상단과 width height

(184, 186, 197, 225)

* 마우스로 다중 ROI 영역 지정 : selectROIs()

In [ ]:
# 만들고 스페이스 한 것에 대해서 esc쳐야 값이 나온다.

In [81]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
rois = cv2.selectROIs('src', src, False, True) #Flase는 격자에 대한 값 True는 찍은 곳은 센터로 둘것인지 아니면 드래그로 할 것인지를 찍는다.

for r in rois:
    cv2.rectangle(src, (r[0], r[1]), (r[0]+r[2], r[1]+r[3]), (255, 255, 255), 3)
    
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

In [37]:
rois #내가 그린 roi들의 리스트다 center가 True라고 중심점이 아니라 좌측, 상단, 너비, 높이이다..

array([[ 74,  15, 244, 348],
       [239, 134, 200, 246]], dtype=int32)

* 블록 평균 영상

In [80]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype=np.uint8)

N = 20
height, width = dst.shape

h = height // N
w = width // N

for i in range(N):
    for j in range(N):
        x = j * w
        y = i * h
        roi = src[y:y+h, x:x+w]
        dst[y:y+h, x:x+w] = roi.mean()
        
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()
# 영역을 만들고 평균을 낸다 모자이크의 효과이다.

In [56]:
src.dtype

dtype('uint8')

In [86]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_COLOR)
dst = np.zeros(src.shape, dtype=np.uint8)

N = 100
height, width = dst.shape[:2] # _ 언더바로 받아도 되는데 안쓰는 것을 _에 받아오는 역할

h = height // N
w = width // N

for i in range(N):
    for j in range(N):
        x = j * w
        y = i * h
        roi = src[y:y+h, x:x+w]
        dst[y:y+h, x:x+w, 0] = roi[:,:,0].mean()
        dst[y:y+h, x:x+w, 1] = roi[:,:,1].mean()
        dst[y:y+h, x:x+w, 2] = roi[:,:,2].mean()
        
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()
# 영역을 만들고 평균을 낸다 모자이크의 효과이다.

* 영상 복사

In [89]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

# dts = src      #참조
dst = src.copy() #복사

dst[100:400, 200:300] = 0

cv2.imshow('src', src) #카피를 해야지 복사본 건드려도 원본이 보존이 된다.
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [101]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

shape = src.shape[0], src.shape[1], 3
dst = np.zeros(shape, dtype=np.uint8)

#dst[:,:,0] = src
dst[:,:,1] = src
dst[:,:,2] = src

cv2.imshow('src', src)
cv2.imshow('dst', dst)

cv2.waitKey()
cv2.destroyAllWindows()

* 채널 분리

In [102]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_COLOR)
dst = cv2.split(src)

In [106]:
len(dst) #3개로 나뉘었다는 것 b g r값이다.

3

In [121]:
dst[0].shape

cv2.imshow('src', src)
cv2.imshow('blue', dst[0]) #아무리 블루에 대한 속성값이라고 해도 2차원인 이상 그레이 스케일이다.
cv2.imshow('green', dst[1])
cv2.imshow('red', dst[2]) #많이 들어간 부분일 수록 밝게 보인다.
cv2.waitKey()
cv2.destroyAllWindows()

In [113]:
type(dst[1])

numpy.ndarray

In [114]:
dst[2]

array([[225, 224, 224, ..., 236, 220, 197],
       [224, 224, 224, ..., 235, 217, 189],
       [224, 224, 225, ..., 230, 215, 190],
       ...,
       [ 82,  81,  92, ..., 175, 175, 175],
       [ 80,  81,  96, ..., 177, 181, 183],
       [ 81,  83,  98, ..., 176, 183, 188]], dtype=uint8)

In [127]:
src = cv2.imread('./data/candies.png', cv2.IMREAD_COLOR)

b, g, r = cv2.split(src)

cv2.imshow('src', src)
cv2.imshow('blue', b) #아무리 블루에 대한 속성값이라고 해도 2차원인 이상 그레이 스케일이다.
cv2.imshow('green', g)
cv2.imshow('red', r) #많이 들어간 부분일 수록 밝게 보인다.

cv2.waitKey()
cv2.destroyAllWindows()

* 채널 병합

In [132]:
merge = cv2.merge([b, g, r])

merge.shape #합쳐진 것을 볼 수 있다.

(480, 640, 3)

* 색 변환

그레이 스케일 영상이 처리속도와 메모리 사용량이 낮기 때문임. 또한 색이라는 것이 도움되지 않는 경우에 특히 그레이 스케일로 영상을 변환한다

cv2.cvtColor(대상, 변환함수)

그레이스케일 변환 공식 = 0.299R + 0.587G + 0.114B 이다

In [ ]:
src = cv2.imread('./data/lena.png', cv2.IMREAD_COLOR)

gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
tCrCv = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

In [ ]:
bgr = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

In [148]:
cv2.imshow('bgr', bgr)
cv2.waitKey()
cv2.destroyAllWindows()

In [139]:
cv2.imshow('gray', gray)
cv2.imshow('tCrCv', tCrCv)
cv2.imshow('hsv', hsv)
cv2.waitKey()
cv2.destroyAllWindows()

In [152]:
512 * 512

262144

In [155]:
(bgr[:, : ,2] == gray).sum() #결국에 그레이 채널을 복사해서 만든 것뿐이다.

262144

* 전단 변환은 x 나 y축을 조금씩 밀어서 평행사변형으로 만드는 것.

* 영상 크기 변환

In [157]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

In [162]:
dst1 = cv2.resize(src, dsize=(320, 240)) #이렇게 사이즈를 직접 지정해도 되고
dst2 = cv2.resize(src, dsize=(0, 0), fx=1.5, fy=1.2) #이런식으로 배수를 정할 수도 있다.

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 회전 변환

In [165]:
src = cv2.imread('./data/lena.jpg')

dst1 = cv2.rotate(src, cv2.ROTATE_90_CLOCKWISE) #시계방향
dst2 = cv2.rotate(src, cv2.ROTATE_90_COUNTERCLOCKWISE) #반시계방향

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

In [175]:
src = cv2.imread('./data/lena.jpg')

height, width, channels = src.shape

M1 = cv2.getRotationMatrix2D((height/2, width/2), 45, 0.5) #y x순으로 집어넣는다.
M2 = cv2.getRotationMatrix2D((height/2, width/2), -45, 0.5) #마지막 1은 스케일 45는 각도

dst1 = cv2.warpAffine(src, M1, (width, height)) #진짜 변환하는 것.
dst2 = cv2.warpAffine(src, M2, (width, height))

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

크기변환 / 전단변환 / 회전변환 / 어파인변환 / 대칭변환 / 투시변환 

* 결국 중요한 건 매트릭스를 설정하는 것이다.

* 영상 어파인 변환 (주어진 세개의 점을 가지고 평행사변형 만들기)

In [178]:
src = cv2.imread('./data/tekapo.bmp')
height, width, channels = src.shape

srcPts = np.float32([[0, 0], [width-1, 0], [width-1, height-1]]) #모서리 세 지점 0, 0, 우측 끝, 우 하단
dstPts = np.float32([[50, 50], [width-100, 100], [width-50, height-50]]) #모서리 세 지점


M = cv2.getAffineTransform(srcPts, dstPts) # 세지점 바꿀 세 지점

dst = cv2.warpAffine(src, M, (width, height))

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [179]:
M.dtype #플롯형이다

dtype('float64')

* 영상 이동 변환 (축소/ 확대)

In [181]:
src = cv2.imread('./data/tekapo.bmp')
height, width, channels = src.shape

M = np.array([[1, 0, 150],
            [0, 1, 100]], dtype=np.float64) # 세지점 바꿀 세 지점

dst = cv2.warpAffine(src, M, (width, height))

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 대칭 변환 (좌, 우/ 상, 하)

In [184]:
src = cv2.imread('./data/eastsea.bmp')

dst1 = cv2.flip(src, 1) # 1 : 좌우 대칭
dst2 = cv2.flip(src, 0) # 0 : 상하 대칭
dst3 = cv2.flip(src, -1) # -1: 좌우 상하

cv2.imshow('src', src)
cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.imshow('dst3', dst3)
cv2.waitKey()
cv2.destroyAllWindows()

cv2.flip(src, 1) # 1 : 좌우 대칭, 0 : 상하 대칭, -1: 좌우 상하

* 투시 변환

In [281]:
src = cv2.imread('./data/card.bmp')
height, width, channels = src.shape
x_y = []
cnt = 0

def onMouse(event, x, y, flags, param):
    global cnt
    if event == cv2.EVENT_LBUTTONDOWN:
        x_y.append([x, y])
        cv2.circle(param[0], (x, y), 5, (255, 0, 0), 3) #param이 여러개를 받아와서 색인으로 해야함
        cnt += 1
    if cnt == 4:
        dst1 = np.array(x_y[:4], np.float32)
        dst2 = np.float32([[0, 0], [width-1, 0], [width - 1, height -1], [0, height-1]])

        M = cv2.getPerspectiveTransform(dst1, dst2)
        dst = cv2.warpPerspective(src, M, (width, height))
        
        cv2.imshow('dst', dst)
        cv2.waitKey()
        cv2.destroyAllWindows()
        return
    
    cv2.imshow('src', param[0])
    
cv2.imshow('src', src)
                          
cv2.setMouseCallback('src', onMouse, [src])
cv2.waitKey()
cv2.destroyAllWindows()

In [267]:
# 재효님 코드
src = cv2.imread('./data/card.bmp')

srcPts = np.zeros((4, 2), dtype=np.float32)
cnt = 0
def onMouse(event, x, y, flags, param):
    global cnt
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(param[0], (x, y), 5, (0, 0, 255), 3)
        srcPts[cnt] = [x, y]
        cnt+= 1
        
        if cnt == 4:
            w = 150
            h = 200
            dstPts = np.float32([[0, 0], [w, 0],
                                [w, h], [0, h]])
            
            
            M = cv2.getPerspectiveTransform(srcPts, dstPts)

            dst = cv2.warpPerspective(src, M, (w, h))
            cv2.imshow('dst', dst)
            
    cv2.imshow('src', param[0])        

cv2.imshow('src', src)
cv2.setMouseCallback('src', onMouse, [src])
cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
height, width = 300, 200

srcQuad = np.zeros((4, 2), dtype=np.float32)
#dstQuad = np.zeros((4, 2), dtype=np.float32)
dstQuad = np.array([[0, 0], [width-1, 0], [width - 1, height -1], [0, height-1]], dtype=np.float32)

cnt = 0

def onMouse(event, x, y, flags, param):
    global cnt
    
    if event == cv2.EVENT_LBUTTONDOWN:
        if cnt < 4:
            srcQuad[cnt] = np.array([x, y], dtype=np.float32)
            cv2.circle(param[0], (x, y), 5, (255, 0, 0), 2)
            cv2.imshow('src', param[0])
            cnt += 1
        if cnt == 4:
            M = cv2.getPerspectiveTransform(srcQuad, dstQuad)
            dst = cv2.warpPerspective(param[0], M, (width, height))
            cv2.imshow('dst', dst)
        
src = cv2.imread('./data/card.bmp')
cv2.imshow('src', src)                          
cv2.setMouseCallback('src', onMouse, [src])

cv2.waitKey()
cv2.destroyAllWindows()

NameError: name 'np' is not defined